version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cania_app
    ports:
      - "9096:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: cania_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: inventoryweb
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3310:3306"
    volumes:
      - ./db/inventoryweb.sql:/docker-entrypoint-initdb.d/init.sql
      - cania_db_data:/var/lib/mysql

volumes:
  cania_db_data:
